# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
  steps: 
    - run: yarn
      shell: bash
    - run: yarn build:prod
      shell: bash
    - run: git config user.name github-actions
      shell: bash
    - run: git config user.email github-actions@github.com
      shell: bash
    - run: git --work-tree build add --all
      shell: bash
    - run: git commit -m "Automatic Deploy action run by github-actions"
      shell: bash
    - run: git push origin HEAD:gh-pages --force
      shell: bash
